//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode+
// http://embedXcode.weebly.com
//
// Project 		Rip-It_Fence
//
// Created by 	john, 1/12/17 11:27 PM
//              john
//
// Copyright 	© john, 2017
// Licence 		All rights reserved
//
// See 			Rip-It_Fence.cpp and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN Rip_It_Fence.cpp
// ----------------------------------
//
// Last update: Jan 06, 2017 release 6.0.2

#include "WProgram.h"

extern "C" int main(void)
{
    setup();
    while (1)
    {
        loop();
        yield();
    }
}

// Sketch
#include "Rocket_Stove_Temp_Cntl.cpp"
